import 'hospital_models.dart';

class HospitalDemoRepository {
  HospitalDemoRepository({DateTime? seedTime})
    : seedTime = seedTime ?? DateTime.now();

  final DateTime seedTime;

  List<HospitalTicket> loadTickets() {
    final now = seedTime;
    return [
      _ticket(
        id: 'QPMS-HH-2026-0108',
        block: 'Block A',
        floor: '1st Floor',
        department: 'Nursing',
        roomArea: 'Nurse Station Washroom',
        location: 'Nurse Station Washroom',
        exactLandmark: 'Opposite nursing station',
        category: 'Washroom Cleaning',
        priority: HospitalPriority.high,
        description: 'Bathroom not cleaned near nurse station.',
        raisedAt: now.subtract(const Duration(minutes: 4, seconds: 36)),
        status: HospitalTicketStatus.open,
        responsiblePerson: 'Supervisor - Block A',
        responsibleRole: 'Housekeeping Supervisor',
      ),
      _ticket(
        id: 'QPMS-HH-2026-0107',
        block: 'Block A',
        floor: 'Ground Floor',
        department: 'OPD',
        roomArea: 'OPD Waiting Area',
        location: 'OPD Waiting Area',
        category: 'Waste Clearance',
        priority: HospitalPriority.high,
        description: 'Dustbin overflow in OPD waiting area.',
        raisedAt: now.subtract(const Duration(minutes: 15, seconds: 10)),
        status: HospitalTicketStatus.inProgress,
        responsiblePerson: 'Supervisor - Block A',
        responsibleRole: 'Housekeeping Supervisor',
        additionalEvents: [
          _event(
            'Accepted',
            'Supervisor - Block A',
            'Housekeeping Supervisor',
            now.subtract(const Duration(minutes: 13)),
            'Complaint accepted.',
          ),
          _event(
            'Work started',
            'Supervisor - Block A',
            'Housekeeping Supervisor',
            now.subtract(const Duration(minutes: 11)),
            'Team sent to clear and sanitize the area.',
          ),
          _event(
            'SLA warning',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 1)),
            'Less than five minutes remain.',
          ),
        ],
      ),
      _ticket(
        id: 'QPMS-HH-2026-0106',
        block: 'Block A',
        floor: '3rd Floor',
        department: 'Administration',
        roomArea: 'Staff Washroom',
        location: 'Staff Washroom',
        category: 'Consumables',
        priority: HospitalPriority.medium,
        description: 'Soap dispenser empty in staff washroom.',
        raisedAt: now.subtract(const Duration(minutes: 22)),
        status: HospitalTicketStatus.resolvedAwaitingConfirmation,
        responsiblePerson: 'Supervisor - Block A',
        responsibleRole: 'Housekeeping Supervisor',
        resolvedAt: now.subtract(const Duration(minutes: 5)),
        resolutionRemarks: 'Soap dispenser refilled and checked.',
        actionTaken: 'Refilled consumable and verified dispenser operation.',
        completionPhotoPaths: const ['demo://soap-complete'],
        additionalEvents: [
          _event(
            'Accepted',
            'Supervisor - Block A',
            'Housekeeping Supervisor',
            now.subtract(const Duration(minutes: 19)),
            'Complaint accepted.',
          ),
          _event(
            'Resolution',
            'Supervisor - Block A',
            'Housekeeping Supervisor',
            now.subtract(const Duration(minutes: 5)),
            'Dispenser refilled and ready.',
            hasPhoto: true,
          ),
        ],
      ),
      _ticket(
        id: 'QPMS-HH-2026-0105',
        block: 'Block A',
        floor: '2nd Floor',
        department: 'Patient Ward',
        roomArea: 'Patient Ward Entrance',
        location: 'Patient Ward Entrance',
        category: 'Wet Area',
        priority: HospitalPriority.high,
        description: 'Wet floor near patient ward entrance.',
        raisedAt: now.subtract(const Duration(hours: 3)),
        status: HospitalTicketStatus.closed,
        responsiblePerson: 'Supervisor - Block A',
        responsibleRole: 'Housekeeping Supervisor',
        resolvedAt: now.subtract(const Duration(hours: 2, minutes: 42)),
        resolutionRemarks:
            'Floor dried and caution signage removed after safety check.',
        actionTaken: 'Mopped, dried and inspected the area.',
        completionPhotoPaths: const ['demo://wet-floor-complete'],
        clientRating: 5,
        clientSatisfied: true,
        clientFeedback: 'Area is clean and safe now.',
        additionalEvents: [
          _event(
            'Resolution',
            'Supervisor - Block A',
            'Housekeeping Supervisor',
            now.subtract(const Duration(hours: 2, minutes: 42)),
            'Area cleaned and made safe.',
            hasPhoto: true,
          ),
          _event(
            'Final closure',
            'Hospital Client User',
            'Client',
            now.subtract(const Duration(hours: 2, minutes: 35)),
            'Satisfied with the completed work.',
          ),
        ],
      ),
      _ticket(
        id: 'QPMS-HH-2026-0104',
        block: 'Block B',
        floor: '2nd Floor',
        department: 'General Ward',
        roomArea: 'General Washroom',
        location: 'General Washroom',
        category: 'Odor Issue',
        priority: HospitalPriority.high,
        description: 'Bad smell in second-floor washroom.',
        raisedAt: now.subtract(const Duration(minutes: 31)),
        status: HospitalTicketStatus.escalatedOperationsExecutive,
        responsiblePerson: 'Arun P.',
        responsibleRole: 'Operations Executive',
        operationsEscalatedAt: now.subtract(const Duration(minutes: 11)),
        operationsDueAt: now.add(const Duration(minutes: 19)),
        additionalEvents: [
          _event(
            'Supervisor notified',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 30)),
            'Block B Supervisor notified.',
          ),
          _event(
            'Supervisor SLA breach',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 11)),
            'Complaint remained unresolved after 20 minutes.',
          ),
          _event(
            'Escalation',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 11)),
            'Escalated to Operations Executive.',
          ),
        ],
      ),
      _ticket(
        id: 'QPMS-HH-2026-0103',
        block: 'Block B',
        floor: 'Ground Floor',
        department: 'ICU',
        roomArea: 'ICU Washroom',
        location: 'ICU Washroom',
        category: 'Washroom Cleaning',
        priority: HospitalPriority.high,
        description: 'ICU washroom cleaning delayed.',
        raisedAt: now.subtract(const Duration(hours: 1, minutes: 8)),
        status: HospitalTicketStatus.escalatedFacilityManager,
        responsiblePerson: 'Priya N.',
        responsibleRole: 'Facility Manager',
        operationsEscalatedAt: now.subtract(const Duration(minutes: 48)),
        operationsDueAt: now.subtract(const Duration(minutes: 18)),
        facilityEscalatedAt: now.subtract(const Duration(minutes: 18)),
        additionalEvents: [
          _event(
            'Supervisor SLA breach',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 48)),
            'Supervisor response exceeded 20 minutes.',
          ),
          _event(
            'Escalation',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 48)),
            'Escalated to Operations Executive.',
          ),
          _event(
            'Operations Executive SLA breach',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 18)),
            'Operations response exceeded 30 minutes.',
          ),
          _event(
            'Escalation',
            'Demo SLA Engine',
            'System',
            now.subtract(const Duration(minutes: 18)),
            'Escalated to Facility Manager.',
          ),
        ],
      ),
      _ticket(
        id: 'QPMS-HH-2026-0102',
        block: 'Block B',
        floor: '1st Floor',
        department: 'Patient Rooms',
        roomArea: 'Patient Room 118',
        location: 'Patient Room 118',
        category: 'Patient Room Cleaning',
        priority: HospitalPriority.high,
        description: 'Patient room requires immediate cleaning.',
        raisedAt: now.subtract(const Duration(minutes: 38)),
        status: HospitalTicketStatus.reopened,
        supervisorDueAt: now.add(const Duration(minutes: 13)),
        responsiblePerson: 'Supervisor - Block B',
        responsibleRole: 'Housekeeping Supervisor',
        resolvedAt: now.subtract(const Duration(minutes: 10)),
        resolutionRemarks: 'Initial room cleaning completed.',
        actionTaken: 'Room surface cleaning and waste removal.',
        completionPhotoPaths: const ['demo://room-complete'],
        clientRating: 2,
        clientSatisfied: false,
        clientFeedback: 'Cleaning behind the bedside cabinet is incomplete.',
        reopenedCount: 1,
        additionalEvents: [
          _event(
            'Resolution',
            'Supervisor - Block B',
            'Housekeeping Supervisor',
            now.subtract(const Duration(minutes: 10)),
            'Room cleaning completed.',
            hasPhoto: true,
          ),
          _event(
            'Reopen',
            'Hospital Client User',
            'Client',
            now.subtract(const Duration(minutes: 7)),
            'Cleaning behind the bedside cabinet is incomplete.',
          ),
        ],
      ),
      _ticket(
        id: 'QPMS-HH-2026-0101',
        block: 'Block B',
        floor: '3rd Floor',
        department: 'General Cleaning',
        roomArea: 'Main Corridor',
        location: 'Main Corridor',
        category: 'General Cleaning',
        priority: HospitalPriority.medium,
        description: 'Corridor floor requires mopping.',
        raisedAt: now.subtract(const Duration(minutes: 8)),
        status: HospitalTicketStatus.assigned,
        responsiblePerson: 'Supervisor - Block B',
        responsibleRole: 'Housekeeping Supervisor',
      ),
      _ticket(
        id: 'QPMS-HH-2026-0100',
        block: 'Block A',
        floor: '',
        department: 'SPL Cardiology OP',
        location: 'Opposite Nursing Station near Lift 2',
        exactLandmark: 'Opposite Nursing Station near Lift 2',
        category: 'General Cleaning',
        priority: HospitalPriority.medium,
        description: 'Landmark-only complaint without confirmed room mapping.',
        raisedAt: now.subtract(const Duration(minutes: 18)),
        status: HospitalTicketStatus.assigned,
        responsiblePerson: 'Supervisor - Block A',
        responsibleRole: 'Housekeeping Supervisor',
      ),
    ];
  }

  HospitalTicket _ticket({
    required String id,
    required String block,
    required String floor,
    String department = '',
    required String location,
    String roomArea = '',
    String exactLandmark = '',
    required String category,
    required HospitalPriority priority,
    required String description,
    required DateTime raisedAt,
    required HospitalTicketStatus status,
    required String responsiblePerson,
    required String responsibleRole,
    DateTime? operationsEscalatedAt,
    DateTime? operationsDueAt,
    DateTime? facilityEscalatedAt,
    DateTime? resolvedAt,
    String resolutionRemarks = '',
    String actionTaken = '',
    List<String> completionPhotoPaths = const [],
    int? clientRating,
    bool? clientSatisfied,
    String clientFeedback = '',
    int reopenedCount = 0,
    DateTime? supervisorDueAt,
    List<HospitalTicketEvent> additionalEvents = const [],
  }) {
    final supervisor = block == 'Block A'
        ? 'Supervisor - Block A'
        : 'Supervisor - Block B';
    return HospitalTicket(
      id: id,
      site: 'NIMS Hyderabad',
      block: block,
      floor: floor,
      department: department,
      location: location,
      roomArea: roomArea,
      exactLandmark: exactLandmark,
      completeLocationPath: [
        'NIMS Hyderabad',
        block,
        floor,
        department,
        roomArea.isEmpty ? location : roomArea,
        exactLandmark,
      ].where((part) => part.trim().isNotEmpty).toSet().join(' > '),
      category: category,
      priority: priority,
      description: description,
      reportedBy: 'Hospital Client User',
      raisedAt: raisedAt,
      status: status,
      responsiblePerson: responsiblePerson,
      responsibleRole: responsibleRole,
      supervisorName: supervisor,
      supervisorDueAt:
          supervisorDueAt ?? raisedAt.add(const Duration(minutes: 20)),
      operationsEscalatedAt: operationsEscalatedAt,
      operationsDueAt: operationsDueAt,
      facilityEscalatedAt: facilityEscalatedAt,
      resolvedAt: resolvedAt,
      resolutionRemarks: resolutionRemarks,
      actionTaken: actionTaken,
      complaintPhotoPaths: const ['demo://complaint'],
      completionPhotoPaths: completionPhotoPaths,
      clientRating: clientRating,
      clientSatisfied: clientSatisfied,
      clientFeedback: clientFeedback,
      reopenedCount: reopenedCount,
      events: [
        _event(
          'Complaint created',
          'Hospital Client User',
          'Client',
          raisedAt,
          description,
          hasPhoto: true,
        ),
        _event(
          'Supervisor notified',
          'Demo SLA Engine',
          'System',
          raisedAt.add(const Duration(seconds: 20)),
          '$supervisor notified.',
        ),
        ...additionalEvents,
      ],
    );
  }

  static HospitalTicketEvent _event(
    String action,
    String actor,
    String role,
    DateTime time,
    String remarks, {
    bool hasPhoto = false,
  }) => HospitalTicketEvent(
    action: action,
    actor: actor,
    actorRole: role,
    occurredAt: time,
    remarks: remarks,
    hasPhoto: hasPhoto,
  );
}
